### ISSUE TITLE
Missing the function for adding background images

### ISSUE THREAD

**Issue by TheHolyEmber** [finneyj/GameArena#13]
After looking through the GameArena files provided, I realised there does not seem to be a function for adding a background image as said in the coursework information (for Carom). 

Hopefully this can be fixed.

**Comment by finneyj** [comment]
Thanks @TheHolyEmber.

I think Ilia was working on a contribution... Not sure of his github id though. I'll ping him on Teams.

**Comment by finneyj** [comment]
Fixed in https://github.com/finneyj/GameArena/commit/12ea102ef616510226bd94761123b8dfda87e327
