### ISSUE TITLE
Rectangle change colour method

### ISSUE THREAD

**Issue by bogga** [finneyj/GameArena#4]
Could you add a rectangle change colour method please?

**Comment by finneyj** [comment]
Yep - good suggestion.

This is actually only a very small change, and only needs accessor and mutator (getColour and setColour) methods to be added to the Rectangle class...

Do you fancy making these simple changes, tetsing it works, and then submitting a Pull Request to this repo? If so, i'd happily merge it?

**Comment by bogga** [comment]
Sure thing!


I'll probably submit it tonight

________________________________

**Comment by finneyj** [comment]
Closing this off as your Pull Request has been merged...
