### ISSUE TITLE
Suggestion, documentation fixes, HashMap issues

### ISSUE THREAD

**Issue by kilanth** [finneyj/GameArena#5]
Please consider this code for GameArena
<code><p>
public static final String BLACK = "#000000";</p><p>
public static final String BLUE = "#0000ff";</p><p>
public static final String CYAN = "#00ffff";</p><p>
public static final String DARKGREY = "#a9a9a9";</p><p>
public static final String GREY = "#808080";</p><p>
public static final String GREEN = "#008000";</p><p>
public static final String LIGHTGREY = "#d3d3d3";</p><p>
public static final String MAGENTA = "#ff00ff";</p><p>
public static final String ORANGE = "#ffa500";</p><p>
public static final String PINK = "#ffc0cb";</p><p>
public static final String RED = "#ff0000";</p><p>
public static final String WHITE = "#ffffff";</p><p>
public static final String YELLOW = "#ffff00";</p>

</code>
So the colours will be accessible through GameArena.BLACK, which will give a better overview of which colours are available for the use for stringToColor(String) method.

In documentation of ball and rectangle, there is a mistake with saying which colour is pure for what colour, e.g. in Ball class it says
<code>
// Pure red is FF0000
// Pure red is 00FF00
// Pure red is 0000FF
</code>

Please suggest reviewing HashMap for drawing objects on the canvas, since HashMap is ordering objects in a really silly way sometimes. Which can result in some Shapes being drawn behind each other even if they were declared in some particular order, e.g. Background for a rolling ball could sometimes go in front of the ball covering the rolling ball, even if Background Rectangle was placed on the canvas first.

**Comment by finneyj** [comment]
Hi @kilanth 

Thanks for feedback - all good points.

For the first two points, this is a very good suggestion. Would you like to make these simple changes fixes and submit a PullRequest (I can talk you through it if it's your first time), then I'll happily merge these changes into the master branch and everyone can benefit.

For the third point, I'm pretty sure I fixed this in a recent commit:
https://github.com/finneyj/GameArena/commit/9a435f373d799c00af4a23031cd8fa02e68cbccb

Are you developing against the latest version of the code, or an older version? The latest version should draw objects on the screen on the order that they are added... Can you verify this?

p.s. just for your information, versioning systems work best when you have one point per issue, so ideally you would raise the above points as three independent issues. That way, it's easier to track the progress of each one, assign the work to different developers etc.

**Comment by finneyj** [comment]
@kilanth? Would you like to submit a Pull request including these additional features/fixes?

**Comment by finneyj** [comment]
@kilanth Would you like the honour of closing this issue, now your patch has been merged?

**Comment by kilanth** [comment]
@finneyj Nah, do it. I don't really mind. Thanks for the whole game dev project thingy, it is quite fun.

**Comment by finneyj** [comment]
:-) No worries. Necessity is the mother of invention... in other words, if you want people to innovate, you need to restrict them. Otherwise the design space is too large... ;-)
