### ISSUE TITLE
Dynamically changing width or height of a Rectangle object

### ISSUE THREAD

**Issue by Mark-McE** [finneyj/GameArena#7]
When adding a Rectangle to the GameArena, and then increasing or decreasing the width or height, the rectangle does not change in width or height, but instead is displaced on the screen such that it's top left corner is in the newly calculated top left corner.
I have found that removing the rectangle from the GameArena and immediately re-adding it shows the rectangle with the correct width and height.

below is a sample program to demonstrate the issue.

    public class test{
      public static void main( String[] args ){
        
        GameArena playerWindow = new GameArena(900,400);
        Rectangle rec = new Rectangle(450,200,100,50,"red");
        playerWindow.addRectangle(rec);
        
        for(;;){
          if(playerWindow.upPressed()){
            rec.setHeight(rec.getHeight()+10);
            //playerWindow.removeRectangle(rec);
            //playerWindow.addRectangle(rec);
          }
          if(playerWindow.downPressed()){
            rec.setHeight(rec.getHeight()-10);
            //playerWindow.removeRectangle(rec);
            //playerWindow.addRectangle(rec);
          }
          if(playerWindow.rightPressed()){
            rec.setWidth(rec.getWidth()+10);
            //playerWindow.removeRectangle(rec);
            //playerWindow.addRectangle(rec);
          }
          if(playerWindow.leftPressed()){
            rec.setWidth(rec.getWidth()-10);
            //playerWindow.removeRectangle(rec);
            //playerWindow.addRectangle(rec);
          }
          playerWindow.pause();
        }
      }
    }

**Comment by finneyj** [comment]
@Mark-McE ooer. That's interesting. :-)

**Comment by finneyj** [comment]
Fixed in master. If you update your copy of the repo, it should now work ok. I've also added accessor/mutator methods for Ball and Rectangle accordingly.
